import Image from "next/image"
import Navbar from "@/components/navbar"
import Footer from "@/components/footer"
import DemoSection from "@/components/demo-section"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

export default function ANPRPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <Navbar activePage="products" />

      {/* Hero Section */}
      <section className="bg-[#171440] py-16 md:py-32 relative">
        {/* Background Image Overlay */}
        <div className="absolute inset-0 bg-[url('/img/products/anprbg.png')] bg-contain bg-center opacity-30"></div>

        {/* Content */}
        <div className="container mx-auto px-4 md:px-10 relative z-10">
          <div className="max-w-2xl">
            <h1 className="text-4xl md:text-6xl font-bold mb-4 text-white leading-tight">
              Fusion <span className="text-[#f16e5a]">ANPR</span>
            </h1>
            <p className="text-white text-base md:text-lg mb-6 leading-relaxed">
              Revolutionize your operations with Fusion ANPR, delivering seamless vehicle tracking and management.
              Boost efficiency, enhance security, and drive growth with real-time insights.
            </p>
          </div>
        </div>
      </section>

      <div className="mx-4 md:mx-12 px-4 md:px-12">
        {/* What is ANPR Section */}
        <section className="py-12">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <Image
                  src="/img/products/aboutanpr.jpg"
                  alt="ANPR Camera View"
                  width={500}
                  height={400}
                  className="w-full h-auto rounded-2xl"
                />
              </div>
              <div>
                <h2 className="text-2xl mb-4 text-black">
                  What is <span className="text-[#171440] font-bold">FUSION ANPR</span>
                </h2>
                <p className="text-gray-600 mb-4">
                  <strong>Fusion ANPR (Automatic Number Plate Recognition)</strong>
                </p>
                <p className="text-gray-600 mb-6">
                  ANPR is a technology that uses computer vision and AI to automatically read and identify vehicle license plates. It enables real-time vehicle tracking, monitoring, and management across various applications such as traffic systems, parking management, toll booths, and security surveillance.
                </p>
                <div >
                  <div className="space-y-4">
                    <div className="flex items-start gap-3">
                      <div className="">
                        <div className="w-4 h-4 mt-1">
                          <Image src="/img/tickicon.png" alt="Tick Icon" width={16} height={16} />
                        </div>
                      </div>
                      <p className="text-[#303030]">Streamlines parking by identifying vehicles and allocating slots instantly.</p>
                    </div>

                    <div className="flex items-start gap-3">
                      <div className="">
                        <div className="w-4 h-4 mt-1">
                          <Image src="/img/tickicon.png" alt="Tick Icon" width={16} height={16} />
                        </div>
                      </div>
                      <p className="text-[#303030]">Enables fast, contactless toll collection for a smoother travel experience.</p>
                    </div>
                  </div>
                </div>
                {/* <Link href="#" className="text-[#f16e5a] font-medium flex items-center">
                  Read More Information
                  <svg
                    className="ml-2 w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"></path>
                  </svg>
                </Link> */}
              </div>
            </div>
          </div>
        </section>

        {/* Our Vision Section */}
        <section className="py-12">
          <div className="container mx-auto px-4">
            <h2 className="text-2xl font-bold mb-4 text-black">Our Vision</h2>
            <p className="text-gray-600 mb-8">
              Transforming your business with insights generated by our Fusion Engine just so that your business
              operations can work smoothly and swiftly which in return will boost your efficiency and profit.{" "}
              <span className="font-bold text-[#f16e5a]">This is FUSION VISION!</span>
            </p>

            {/* <div className="flex justify-center my-12">
              <Image
                src="/img/products/visionanpr.png"
                alt="ANPR Process Flow"
                width={800}
                height={100}
                className="w-full max-w-3xl h-auto"
              />
            </div> */}
          </div>
        </section>

        {/* Features Section */}
        <section className="py-16 bg-gray-50">
          <div className="container mx-auto px-4">
            <h2 className="text-2xl font-bold mb-12 text-black">Features</h2>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="bg-[#F7F6F8] p-6 rounded-xl shadow-sm">
                <div className="flex justify-center mb-6">
                  <Image
                    src="/img/products/intelligent transport.png"
                    alt="Intelligent Transport"
                    width={120}
                    height={120}
                    className="h-32 w-auto"
                  />
                </div>
                <h3 className="text-xl font-bold mb-4 text-black">Intelligent Transport</h3>
                <p className="text-gray-600 mb-6">
                  Leverage real-time license plate recognition to optimize traffic movement, identify vehicle trends, and
                  enforce automated rules. Fusion ANPR aids smart city development by enabling efficient route monitoring,
                  congestion management, and illegal vehicle detection.
                </p>
              </div>

              <div className="bg-[#F7F6F8] p-6 rounded-xl shadow-sm">
                <div className="flex justify-center mb-6">
                  <Image
                    src="/img/products/traffic management.png"
                    alt="Traffic Management"
                    width={120}
                    height={120}
                    className="h-32 w-auto"
                  />
                </div>
                <h3 className="text-xl font-bold mb-4 text-black">Traffic Management</h3>
                <p className="text-gray-600 mb-6">
                  Streamline urban mobility with automated vehicle identification. Fusion ANPR integrates with traffic
                  lights, surveillance systems, and analytics dashboards to enhance planning, reduce bottlenecks, and
                  increase road safety.
                </p>
              </div>

              <div className="bg-[#F7F6F8] p-6 rounded-xl shadow-sm">
                <div className="flex justify-center mb-6">
                  <Image
                    src="/img/products/intelligent  parking.png"
                    alt="Intelligent Parking"
                    width={120}
                    height={120}
                    className="h-32 w-auto"
                  />
                </div>
                <h3 className="text-xl font-bold mb-4 text-black">Intelligent Parking</h3>
                <p className="text-gray-600 mb-6">
                  Simplify and secure parking operations with automated entry/exit based on number plate recognition. Reduce
                  wait times, prevent unauthorized access, and maximize space utilization through real-time slot tracking
                  and automated billing.
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>

      <section className="py-20 relative overflow-hidden">
        {/* Background Pattern */}
        <div className="absolute inset-0 bg-[#28236B]">
          <div className="absolute inset-0">
            <Image
              src="/img/products/bg.png"
              alt="Background Pattern"
              fill
              className="object-cover"
            />
          </div>
        </div>

        <div className="relative bg-cover bg-center min-h-[200px] flex items-center justify-center text-white" style={{ backgroundImage: "url('/img/products/banner-bg.png')" }}>
          <div className="container mx-auto text-center z-10 px-4 py-10">
            {/* Logo */}
            <div className="flex justify-center mb-6">
              <Image src="/img/products/logo-white.png" alt="The Fusion Apps" width={250} height={80} />
            </div>

            {/* Quote */}
            <h2 className="text-xl md:text-3xl font-bold leading-snug">
              Marketing Shapes a Story,<br />
              <span className="block">Conversion Alters it into Effects.</span>
            </h2>
          </div>
        </div>
      </section>

      <div className="mx-4 md:mx-12 px-4 md:px-12">
        {/* Problem vs Solution Section */}
        <section className="py-16">
          <div className="container mx-auto px-4">
            <h2 className="text-2xl font-bold mb-8 uppercase text-black">PROBLEM vs SOLUTION</h2>
            <p className="text-gray-600 mb-12">
              In a typical cloud deployment, a video processing unit is established on-site, complemented by additional
              resources hosted on a modern cloud server provider. This approach seamlessly integrates on-premises and
              cloud components, offering scalability and flexibility while meeting regulatory requirements and keeping
              costs under control.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="bg-gray-100 p-6 rounded-xl">
                <div className="flex items-center mb-4">
                  <div className="bg-yellow-500 p-2 rounded-lg mr-3">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                        stroke="#000"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold uppercase text-yellow-500">PROBLEM</h3>
                </div>

                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Manual traffic monitoring is slow and inefficient</li>
                  <li>Parking management is time-consuming and space is underutilized</li>
                  <li>Toll booths cause congestion and delays</li>
                  <li>Lack of data for traffic planning in urban areas</li>
                  <li>Difficulty identifying vehicles involved in violations or crimes</li>
                </ul>
              </div>

              <div className="bg-[#FEE4DC] p-6 rounded-xl">
                <div className="flex items-center mb-4">
                  <div className="bg-[#f16e5a] p-2 rounded-lg mr-3">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path
                        d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                        stroke="#fff"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold uppercase text-[#f16e5a]">SOLUTION</h3>
                </div>

                <ul className="list-disc pl-6 space-y-2 text-gray-600">
                  <li>Real-time vehicle identification streamlines traffic flow</li>
                  <li>Automated license plate recognition improves parking allocation and efficiency</li>
                  <li>ANPR enables seamless, automated toll collection</li>
                  <li>ANPR provides analytics for intelligent transportation planning</li>
                  <li>Instant plate recognition improves law enforcement accuracy</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
      </div>

      <section className="py-16">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold mb-8 text-center text-black">
            Frequently Asked <span className="text-[#534F89]">Questions</span>
          </h2>
          <p className="text-center text-gray-500 mb-12 max-w-3xl mx-auto">
            {/* What is Fusion Analytics and how does it help businesses? */}
          </p>

          <div className="mx-4 md:mx-12">
            <Accordion type="single" collapsible className="space-y-4">
              <AccordionItem value="item-1" className="border border-gray-200 rounded-lg overflow-hidden">
                <AccordionTrigger className="px-6 py-4 hover:no-underline hover:bg-gray-50 group text-black">
                  <div className="flex justify-between items-center w-full">
                    <span className="text-left font-medium text-black">
                      How accurate is Fusion ANPR in reading number plates?
                    </span>

                  </div>
                </AccordionTrigger>
                <AccordionContent className="px-6 pb-4 pt-2 text-gray-600">
                  Fusion ANPR offers high-accuracy plate recognition even in challenging conditions such as low light, high speed, or bad weather.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="item-2" className="border border-gray-200 rounded-lg overflow-hidden">
                <AccordionTrigger className="px-6 py-4 hover:no-underline hover:bg-gray-50 group text-black">
                  <div className="flex justify-between items-center w-full">
                    <span className="text-left font-medium text-black">
                      Can Fusion ANPR integrate with my existing surveillance or parking system?
                    </span>

                  </div>
                </AccordionTrigger>
                <AccordionContent className="px-6 pb-4 pt-2 text-gray-600">
                  Yes, it is designed to integrate seamlessly with most existing infrastructure, including cameras, boom barriers, and software.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="item-3" className="border border-gray-200 rounded-lg overflow-hidden">
                <AccordionTrigger className="px-6 py-4 hover:no-underline hover:bg-gray-50 group text-black">
                  <div className="flex justify-between items-center w-full">
                    <span className="text-left font-medium text-black">
                      Is ANPR data stored securely?
                    </span>

                  </div>
                </AccordionTrigger>
                <AccordionContent className="px-6 pb-4 pt-2 text-gray-600">
                  Absolutely. Fusion ANPR follows strict data privacy and encryption protocols to ensure secure storage and access of vehicle data.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="item-4" className="border border-gray-200 rounded-lg overflow-hidden">
                <AccordionTrigger className="px-6 py-4 hover:no-underline hover:bg-gray-50 group text-black">
                  <div className="flex justify-between items-center w-full">
                    <span className="text-left font-medium text-black">
                      What types of license plates does Fusion ANPR support?
                    </span>

                  </div>
                </AccordionTrigger>
                <AccordionContent className="px-6 pb-4 pt-2 text-gray-600">
                  It supports a wide range of plate types and formats, including regional, customized, and international plates.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
        </div>
      </section>

      {/* <FaqSection /> */}
      <DemoSection />
      <Footer />
    </div>
  )
}
